version: '3.9'

services:
  app:
    build:
      context: .
      target: ${TARGET:-development}
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongo:27017/test
    ports:
      - '8081:8080'
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.5-jammy
    ports:
      - '27017:27017'
